DROP TABLE IF EXISTS userLogin;
DROP TABLE IF EXISTS userInfo;
DROP TABLE IF EXISTS history;

CREATE TABLE userInfo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    age INTEGER NOT NULL,
    gender TEXT DEFAULT NONE,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE history (
    Gid INTEGER PRIMARY KEY AUTOINCREMENT,
    usid INTEGER NOT NULL,
    trackName TEXT NOT NULL,
    genre TEXT NOT NULL,
    stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usid) REFERENCES userInfo (id)
);
